on:
  workflow_dispatch:
  push:
    paths:
      - 'modules.yaml'
  schedule:
    - cron: '0 0 * * *'  # Run daily to check for updates

jobs:
  check_updates:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
      caddy_version: ${{ steps.check.outputs.caddy_version }}
      custom_version: ${{ steps.check.outputs.custom_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for updates
        id: check
        run: |
          # Check Caddy releases
          LATEST_CADDY=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)
          CURRENT_CADDY=$(cat .caddy_version || echo "v0.0.0")
          
          # Generate hash of modules.yaml
          MODULES_HASH=$(sha256sum modules.yaml | cut -d ' ' -f 1)
          
          # Check if we need to build
          if [ "$LATEST_CADDY" != "$CURRENT_CADDY" ] || [ "${{ github.event_name }}" == "push" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo $LATEST_CADDY > .caddy_version
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "caddy_version=$LATEST_CADDY" >> $GITHUB_OUTPUT
            echo "custom_version=${LATEST_CADDY#v}-${MODULES_HASH:0:8}" >> $GITHUB_OUTPUT
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi

  build_and_release:
    needs: check_updates
    if: needs.check_updates.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Caddy
        run: |
          CADDY_VERSION=${{ needs.check_updates.outputs.caddy_version }}
          MODULES=$(yq e '.modules[].caddy-module' modules.yaml | xargs -I {} echo --with {})
          GOOS=linux
          GOARCH=${{ matrix.arch }}
          
          docker run --rm -v $PWD:/workspace \
            -e GOOS=linux -e GOARCH=${{ matrix.arch }} \
            caddy:${CADDY_VERSION#v}-builder-alpine \
            xcaddy build $MODULES --output /workspace/caddy-$GOOS-$GOARCH

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: caddy-linux-${{ matrix.arch }}
          path: caddy-linux-${{ matrix.arch }}

  create_release:
    needs: [check_updates, build_and_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Prepare Release Notes
        id: release_notes
        run: |
          echo "Custom Caddy Build" > release_notes.md
          echo "" >> release_notes.md
          echo "Version: ${{ needs.check_updates.outputs.custom_version }}" >> release_notes.md
          echo "Based on Caddy ${{ needs.check_updates.outputs.caddy_version }}" >> release_notes.md
          echo "" >> release_notes.md
          echo "Included modules:" >> release_notes.md
          yq e '.modules[].caddy-module' modules.yaml >> release_notes.md
          
      - name: Check for existing release
        id: check_release
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ needs.check_updates.outputs.custom_version }}" \
            | jq -r '.id')
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      - name: Delete existing release if it exists
        if: steps.check_release.outputs.release_id != 'null'
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.check_release.outputs.release_id }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.check_updates.outputs.custom_version }}
          release_name: Custom Caddy ${{ needs.check_updates.outputs.custom_version }}
          body_path: release_notes.md
          draft: false
          prerelease: false

      - name: Upload Release Asset (amd64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./caddy-linux-amd64/caddy-linux-amd64
          asset_name: caddy-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (arm64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./caddy-linux-arm64/caddy-linux-arm64
          asset_name: caddy-linux-arm64
          asset_content_type: application/octet-stream