name: Convert Modules YAML to JSON

on:
  workflow_dispatch:
  push:
    paths:
      - 'modules.yaml'

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      - name: Convert YAML to JSON
        run: |
          yq -o=json modules.yaml > .github/workflows/modules.json
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit if changed
        run: |
          git add modules.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update modules.json from modules.yaml")

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}