name: Convert Modules YAML to JSON

on:
  push:
    paths:
      - 'modules.yaml'

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      - name: Convert YAML to JSON
        run: |
          yq -o=json modules.yaml > .github/workflows/modules.json
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/workflows/modules.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update modules.json from modules.yaml" && git push)
